using System.Net;

namespace ArangoDBNetStandard.GraphApi
{
    /// <summary>
    /// Represents a response containing information about the created edge in a graph.
    /// </summary>
    public class PostGraphEdgeResponse<T>
    {
        /// <summary>
        /// Indicates whether an error occurred (false in this case).
        /// </summary>
        public bool Error { get; set; }

        /// <summary>
        /// The HTTP status code.
        /// </summary>
        public HttpStatusCode Code { get; set; }

        /// <summary>
        /// The internal attributes for the edge.
        /// </summary>
        public EdgeResult Edge { get; set; }

        /// <summary>
        /// The complete newly written edge document.
        /// Includes all written attributes in <see cref="T"/> and all internal attributes generated by ArangoDB.
        /// Will only be present if <see cref="PostGraphEdgeQuery.ReturnNew"/> is true.
        /// </summary>
        public T New { get; set; }
    }
}
