using System.Net;

namespace ArangoDBNetStandard.GraphApi.Models
{
    public class PostVertexResponse<T>
    {
        /// <summary>
        /// The complete newly written vertex document. 
        /// Includes all written attributes in the request 
        /// body and all internal attributes generated by ArangoDB. 
        /// Will only be present if 
        /// <see cref="PostVertexQuery.ReturnNew"/> is true.
        /// </summary>
        public  T New { get; set; }

        public PostVertexResult Vertex { get; set; }

        public HttpStatusCode Code { get; set; }

        /// <summary>
        /// Indicates whether an error occurred
        /// </summary>
        /// <remarks>
        /// Note that in cases where an error occurs, the ArangoDBNetStandard
        /// client will throw an <see cref="ApiErrorException"/> rather than
        /// populating this property. A try/catch block should be used instead
        /// for any required error handling.
        /// </remarks>
        public bool Error { get; set; }
    }
}
