using ArangoDBNetStandard.AuthApi.Models;
using System.Threading.Tasks;

namespace ArangoDBNetStandard.AuthApi
{
    /// <summary>
    /// Defines a client to access the ArangoDB Authentication API.
    /// </summary>
    public interface IAuthApiClient
    {
        /// <summary>
        /// Gets a JSON Web Token generated by the ArangoDB server.
        /// </summary>
        /// <param name="username">The username of the user for whom to generate a JWT token.</param>
        /// <param name="password">The user's password.</param>
        /// <returns>Object containing the encoded JWT token value.</returns>
        Task<JwtTokenResponse> GetJwtTokenAsync(string username, string password);

        /// <summary>
        /// Gets a JSON Web Token generated by the ArangoDB server.
        /// </summary>
        /// <param name="body">Object containing username and password.</param>
        /// <returns>Object containing the encoded JWT token value.</returns>
        Task<JwtTokenResponse> GetJwtTokenAsync(JwtTokenRequestBody body);
    }
}
